### ISSUE TITLE
CUDA backend for faster host-device transfers

### ISSUE THREAD

**Issue by awnawab** [ecmwf-ifs/field_api#7]
I propose the addition of a CUDA backend, that would allow FIELDs to be allocated in pinned host memory and therefore speedup host-to-device transfers by 2x. This would be an addition to the current OpenACC backend. The CUDA backend would be an opt-in (OFF by default). Crucially, backwards compatibility will be maintained; performance and API will be unaffected in the absence of CUDA.

Another possibility afforded by the CUDA backend is the ability to bypass the OpenACC map, thereby removing the need for shadow-host allocations for `FIELD%DEVPTR`. The shadow host allocations are mandated by the need to register discontiguous wrapped FIELDs in the OpenACC map. `FIELD%DEVPTR` therefore becomes a true device-pointer, rather than a host-pointer associated with a device-pointer. This does have an effect on the API. If the CUDA backend is enabled, then we must replace all `!$acc data present` statements with `!$acc data deviceptr` statements.

**Comment by dareg** [comment]
Seems to be a good proposition, but we'll need to see the implementation obviously.
It's also not a problem if using it require to change all the 'present' statement with 'deviceptr', it's all done with a script anyway.

**Comment by lukasm91** [comment]
I agree, this would be very useful. I actually just yesterday implemented a branch where I improve non-contiguous data. I think this might also happen in IFS, though it certainly depends on the memory layout, but I think there are arrays called GMV/GMVS which are of type (NPROMA,NLEV,NFLD,NBLK), and if  we want to copy (:,:,1:20,:), this is very slow. 
For non-contiguous data types, using cudaMemcpy2D instead of the OpenACC cudaMemcpy(1D) equivalent understandably improves performance of those copies by order of magnitude. Of course, this is tangential to this request because pinned memory helps in both cases, but just want to make sure we don't overlap.

**Comment by awnawab** [comment]
Ah that would be an amazing addition, thanks @lukasm91! Because this might affect another development I have in the pipeline for GMV/GFL arrays (will file issue soon for discussion), is cudaMemcpy2D as fast as if the array were contiguous? Or is there still some small performance penalty from copying discontiguous arrays?

**Comment by lukasm91** [comment]
In general, it is only a small penalty, if at all. This is some measurement I took on A100, with a pingpong copy from a pinned buffer to a device buffer. Just ran it fro a few nx/ny/strides and compare the achieved bandwidth between a contiguous 1D copy, and a strided 2D copy.

```
nx;ny;pitch;bw_1d;bw_2d
32;1048576;64;26.3239;25.8283
64;524288;128;26.3238;22.953
128;262144;256;26.324;25.2391
256;131072;512;26.3238;25.2491
512;65536;1024;26.3154;25.2526
1024;32768;2048;26.3161;26.3116
2048;16384;4096;26.3246;26.3008
4096;8192;8192;26.3233;26.3107
8192;4096;16384;26.3229;25.8543
16384;2048;32768;26.3226;26.3144
32768;1024;65536;26.3225;26.0853
24;1048576;32;26.3093;22.8305
48;524288;64;26.3105;25.0218
96;262144;128;26.3099;25.952
192;131072;256;26.3099;25.9473
384;65536;512;26.3093;26.2712
768;32768;1024;26.3088;26.2661
1536;16384;2048;26.3063;26.2778
3072;8192;4096;26.3091;26.2992
6144;4096;8192;26.3088;26.293
12288;2048;16384;26.3094;26.3004
24576;1024;32768;26.3085;26.1427
```
